# Generated by Django 2.2.3 on 2023-07-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0004_auto_20230720_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doc_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RequestHandler.Doctor'),
        ),
    ]
