# Generated by Django 2.2.3 on 2023-07-20 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RequestHandler', '0005_patient_doc_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='hp_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
