# Generated by Django 2.2.3 on 2023-07-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0007_auto_20230721_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hp_uuid',
            new_name='hospital',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='hp_uuid',
            new_name='hospital',
        ),
    ]
