# Generated by Django 2.2.3 on 2023-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0008_auto_20230721_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.IntegerField(null=True),
        ),
    ]
