# Generated by Django 2.2.3 on 2023-07-22 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0010_auto_20230722_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='doctors/doc1.png', upload_to='doctors'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RequestHandler.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='patients/pat1.png', upload_to='patients'),
        ),
    ]
