# Generated by Django 2.2.3 on 2023-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0012_auto_20230722_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=65)),
                ('units', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=35)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'parámetro',
                'verbose_name_plural': 'parámetros',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('chapter', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'procedimiento',
                'verbose_name_plural': 'procedimientos',
            },
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='result',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='type',
        ),
    ]
