# Generated by Django 2.2.3 on 2023-07-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0013_auto_20230722_1624'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'visita', 'verbose_name_plural': 'visitas'},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='treatment',
        ),
        migrations.AddField(
            model_name='visit',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RequestHandler.Procedure'),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
