# Generated by Django 2.2.3 on 2023-07-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0014_auto_20230722_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='procedure',
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
