# Generated by Django 2.2.3 on 2023-07-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0015_auto_20230722_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('subsection', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('chapter', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'procedimiento',
                'verbose_name_plural': 'procedimientos',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='RequestHandler.Procedure'),
        ),
    ]
