# Generated by Django 2.2.3 on 2023-07-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0016_auto_20230722_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='hp_uuid',
            new_name='hospital',
        ),
    ]
