# Generated by Django 2.2.3 on 2023-07-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0017_auto_20230722_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
    ]
