# Generated by Django 4.2.5 on 2023-09-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0018_auto_20230723_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='procedure',
        ),
        migrations.AddField(
            model_name='visit',
            name='cause',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
