# Generated by Django 4.2.5 on 2023-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RequestHandler', '0019_remove_visit_procedure_visit_cause_delete_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='cause',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
