# Generated by Django 2.2.3 on 2023-07-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginHandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital_name',
            field=models.CharField(default='SUPERUSUARIO', max_length=65),
            preserve_default=False,
        ),
    ]
